# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_notification_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='type, requestId / articleId / complaintId для диплинка')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_status', models.CharField(default='none', max_length=20)),
                ('push_after', models.DateTimeField(blank=True, db_index=True, help_text='Отложено из-за тихих часов', null=True)),
                ('is_promo', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PushTemplate',
            fields=[
                ('kind', models.CharField(choices=[('request.credited', 'Кешбек начислен'), ('request.rejected', 'Заявка отклонена'), ('tier.upgraded', 'Новый уровень'), ('points.expiring', 'Баллы скоро сгорят'), ('points.expired', 'Баллы сгорели'), ('points.adjusted', 'Корректировка баллов'), ('complaint.reply', 'Ответ на обращение'), ('campaign', 'Рассылка')], max_length=40, primary_key=True, serialize=False)),
                ('title', models.JSONField(default=dict)),
                ('body', models.JSONField(default=dict, help_text='Плейсхолдеры: {points}, {tier}, {number}, {days}, {item}')),
            ],
            options={
                'verbose_name': 'Шаблон push',
                'verbose_name_plural': 'Шаблоны push',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict)),
                ('body', models.JSONField(default=dict)),
                ('segment', models.JSONField(default=dict, help_text='{"tiers": [...], "languages": [...]} — пусто = все')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('cancelled', 'Отменена')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stats', models.JSONField(default=dict, help_text='sent, delivered, opened, skipped')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.article')),
            ],
            options={
                'verbose_name': 'Push-рассылка',
                'verbose_name_plural': 'Push-рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
