# Generated by Django 5.2.6 on 2026-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtemplate',
            name='kind',
            field=models.CharField(choices=[('request.credited', 'Кешбек начислен'), ('request.rejected', 'Заявка отклонена'), ('request.paid', 'Оплачено баллами'), ('tier.upgraded', 'Новый уровень'), ('points.expiring', 'Баллы скоро сгорят'), ('points.expired', 'Баллы сгорели'), ('points.adjusted', 'Корректировка баллов'), ('complaint.reply', 'Ответ на обращение'), ('campaign', 'Рассылка')], max_length=40, primary_key=True, serialize=False),
        ),
    ]
