# Generated by Django 5.2.6 on 2026-10-05 19:24

from django.db import migrations, models


def drop_expiry_templates(apps, schema_editor):
    """Баллы больше не сгорают — шаблоны points.expiring / points.expired не нужны."""
    apps.get_model('notifications', 'PushTemplate').objects.filter(
        kind__in=['points.expiring', 'points.expired']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_pushtemplate_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtemplate',
            name='body',
            field=models.JSONField(default=dict, help_text='Плейсхолдеры: {points}, {tier}, {number}, {days}, {item}, {left}, {limit}, {year}, {achievement}'),
        ),
        migrations.AlterField(
            model_name='pushtemplate',
            name='kind',
            field=models.CharField(choices=[('request.credited', 'Кешбек начислен'), ('request.rejected', 'Заявка отклонена'), ('request.paid', 'Оплачено баллами'), ('tier.upgraded', 'Новый уровень'), ('tier.downgraded', 'Уровень понижен'), ('tier.retained', 'Уровень подтверждён'), ('tier.at_risk', 'Подтвердите уровень'), ('achievement.completed', 'Задание выполнено'), ('points.adjusted', 'Корректировка баллов'), ('complaint.reply', 'Ответ на обращение'), ('campaign', 'Рассылка')], max_length=40, primary_key=True, serialize=False),
        ),
        migrations.RunPython(drop_expiry_templates, migrations.RunPython.noop),
    ]
