# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит-лог',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_som', models.PositiveIntegerField(default=100, verbose_name='Баллов за 1 сом')),
                ('birthday_multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Множитель дня рождения')),
                ('birthday_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='Окно ДР: дней до')),
                ('birthday_days_after', models.PositiveSmallIntegerField(default=3, verbose_name='Окно ДР: дней после')),
                ('auto_confirm', models.BooleanField(default=False, verbose_name='Автоподтверждение заявок')),
                ('auto_confirm_cash', models.BooleanField(default=False, verbose_name='Автоподтверждение и для наличных')),
                ('confirm_delay_ms', models.PositiveIntegerField(default=5000, verbose_name='Задержка автоподтверждения, мс')),
                ('credit_delay_ms', models.PositiveIntegerField(default=2500, verbose_name='Задержка начисления после подтверждения, мс')),
                ('pending_ttl_hours', models.PositiveIntegerField(default=72, verbose_name='Срок жизни заявки в pending, ч')),
                ('staff_adjust_threshold_percent', models.PositiveSmallIntegerField(default=20, verbose_name='Правка суммы сотрудником без менеджера, %')),
                ('staff_cashback_limit_points', models.PositiveIntegerField(default=1000000, verbose_name='Кешбек выше лимита — подтверждает менеджер, баллов')),
                ('expiry_months', models.PositiveSmallIntegerField(default=12, verbose_name='Сгорание баллов без активности, мес')),
                ('expiry_warn_days', models.JSONField(default=list, verbose_name='Предупреждать о сгорании за N дней')),
                ('purge_days', models.PositiveSmallIntegerField(default=30, verbose_name='Хранение удалённого аккаунта, дней')),
                ('otp_length', models.PositiveSmallIntegerField(default=4, verbose_name='Длина SMS-кода')),
                ('otp_ttl_seconds', models.PositiveIntegerField(default=120, verbose_name='Срок жизни кода, с')),
                ('otp_retry_seconds', models.PositiveIntegerField(default=60, verbose_name='Повторный запрос кода через, с')),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Попыток ввода кода')),
                ('otp_per_phone_day', models.PositiveSmallIntegerField(default=10, verbose_name='SMS на номер в сутки')),
                ('otp_per_ip_hour', models.PositiveSmallIntegerField(default=20, verbose_name='SMS с одного IP в час')),
                ('min_age', models.PositiveSmallIntegerField(default=16, verbose_name='Минимальный возраст')),
                ('test_enabled', models.BooleanField(default=False, verbose_name='Тестовый аккаунт включён')),
                ('test_phone', models.CharField(blank=True, max_length=20, verbose_name='Тестовый номер')),
                ('test_code', models.CharField(blank=True, max_length=8, verbose_name='Фиксированный код')),
                ('min_version_ios', models.CharField(default='0.0.0', max_length=20, verbose_name='Мин. версия iOS')),
                ('min_version_android', models.CharField(default='0.0.0', max_length=20, verbose_name='Мин. версия Android')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Техработы')),
                ('maintenance_message', models.JSONField(blank=True, default=dict, verbose_name='Текст о техработах')),
                ('resort_phone', models.CharField(default='+996312000000', max_length=30, verbose_name='Телефон курорта')),
                ('resort_whatsapp', models.CharField(default='996555000000', max_length=30, verbose_name='WhatsApp (без +)')),
                ('resort_maps_url', models.URLField(blank=True, default='https://maps.app.goo.gl/baytur', verbose_name='Карта')),
                ('promo_push_monthly_limit', models.PositiveSmallIntegerField(default=4, verbose_name='Рекламных push в месяц')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Тихие часы с')),
                ('quiet_hours_end', models.TimeField(default='09:00', verbose_name='Тихие часы до')),
                ('notification_retention_days', models.PositiveSmallIntegerField(default=30, verbose_name='Хранить уведомления, дней')),
                ('complaint_first_response_hours', models.PositiveSmallIntegerField(default=4, verbose_name='Срок первого ответа, ч')),
                ('complaint_daily_limit', models.PositiveSmallIntegerField(default=5, verbose_name='Новых обращений в сутки на клиента')),
                ('complaint_alert_emails', models.JSONField(blank=True, default=list, verbose_name='Email для уведомлений об обращениях')),
                ('member_qr_ttl_seconds', models.PositiveSmallIntegerField(default=90, verbose_name='Срок жизни QR участника, с')),
                ('analytics_raw_retention_days', models.PositiveIntegerField(default=395, verbose_name='Хранить сырые события, дней')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки программы',
                'verbose_name_plural': 'Настройки программы',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_upload_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('complaint', 'Фото к обращению')], default='image', max_length=20)),
                ('file', models.FileField(max_length=255, upload_to=apps.common.models.upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
