# Generated by Django 5.2.6 on 2026-09-28 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Тихие часы до'),
        ),
        migrations.AlterField(
            model_name='programsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Тихие часы с'),
        ),
    ]
