# Generated by Django 5.2.6 on 2026-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_programsettings_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('complaint', 'Фото к обращению'), ('avatar', 'Аватар')], default='image', max_length=20),
        ),
    ]
