# Generated by Django 5.2.6 on 2026-10-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_upload_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsettings',
            name='expiry_months',
        ),
        migrations.RemoveField(
            model_name='programsettings',
            name='expiry_warn_days',
        ),
    ]
