# Generated by Django 5.2.6 on 2026-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_points_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsettings',
            name='staff_adjust_threshold_percent',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Правка суммы администратором без директора, %'),
        ),
        migrations.AlterField(
            model_name='programsettings',
            name='staff_cashback_limit_points',
            field=models.PositiveIntegerField(default=1000000, verbose_name='Кешбек выше лимита — подтверждает директор, баллов'),
        ),
    ]
