# Generated by Django 5.2.6 on 2026-10-07 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_roles_director_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='base_cashback_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=6, verbose_name='Базовая ставка кешбека (0.05 = 5 % = 10/200)'),
        ),
        migrations.AlterField(
            model_name='programsettings',
            name='points_per_som',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллов за 1 сом'),
        ),
    ]
