# Generated by Django 5.2.6 on 2026-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_points_per_som_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsettings',
            name='staff_cashback_limit_points',
            field=models.PositiveIntegerField(default=10000, verbose_name='Кешбек выше лимита — подтверждает директор, баллов'),
        ),
    ]
