# Generated by Django 5.2.6 on 2026-10-09 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_staff_limit_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsettings',
            name='base_cashback_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='0.05 = 10/200: за 100 000 сом — 5 000 баллов; надбавка уровня умножает (Уровни → «Надбавка к кешбеку»)', max_digits=6, verbose_name='Начисление: баллов за 1 сом оплаты деньгами (Бронза)'),
        ),
        migrations.AlterField(
            model_name='programsettings',
            name='points_per_som',
            field=models.PositiveIntegerField(default=10, help_text='Курс списания при оплате баллами. На начисление не влияет', verbose_name='Оплата баллами: баллов за 1 сом'),
        ),
    ]
