# Generated by Django 5.2.6 on 2026-10-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_restore_points_per_som'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='sk_mode',
            field=models.CharField(blank=True, choices=[('', 'Автоматически по датам'), ('ski', 'Зима — Baytur Ski'), ('kymyz', 'Лето — Baytur Kymyz')], default='', help_text='Выбранный сезон видят все пользователи приложения, даты не учитываются', max_length=10, verbose_name='Сезон Baytur S&K'),
        ),
    ]
