# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackRequest',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_request_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('credited', 'Кешбек начислен'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('timeline', models.JSONField(default=dict)),
                ('item_snapshot', models.JSONField()),
                ('rules', models.JSONField(help_text='{rate, maxPointsShare, methods, pointsPerSom} с учётом акции/ДР')),
                ('bonuses', models.JSONField(blank=True, default=list)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('check_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_points_som', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.PositiveIntegerField()),
                ('points_som', models.PositiveIntegerField()),
                ('points', models.PositiveBigIntegerField()),
                ('money_som', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cashback', models.PositiveBigIntegerField()),
                ('original_total', models.PositiveIntegerField(blank=True, null=True)),
                ('reject_code', models.CharField(blank=True, max_length=30)),
                ('reject_reason', models.TextField(blank=True)),
                ('adjust_reason', models.TextField(blank=True)),
                ('cash_received', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(blank=True, max_length=200)),
                ('proposed_total', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_confirm_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('credit_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('is_test', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка на кешбек',
                'verbose_name_plural': 'Заявки на кешбек',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
