# Generated by Django 5.2.6 on 2026-09-28 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashback', '0001_initial'),
        ('catalog', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackrequest',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_requests', to='members.member'),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.outlet'),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashbackrequest',
            index=models.Index(fields=['member', '-created_at'], name='cashback_ca_member__3423c0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbackrequest',
            index=models.Index(fields=['outlet', 'status'], name='cashback_ca_outlet__5efb7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashbackrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('member', 'idempotency_key'), name='request_idempotency_unique'),
        ),
    ]
