# Generated by Django 5.2.6 on 2026-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackrequest',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда заявка вышла из pending (confirm/reject/cancel)', null=True),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='credited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbackrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
