# Generated by Django 5.2.6 on 2026-10-07 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0003_cashbackrequest_adjusted_at_and_more'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Фискальные реквизиты из QR или хеш содержимого QR', max_length=200, unique=True, verbose_name='Номер чека')),
                ('raw', models.TextField(verbose_name='Содержимое QR')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма, сом')),
                ('fields', models.JSONField(blank=True, default=dict, verbose_name='Распознанные поля')),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Принят')),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.outlet')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipt', to='cashback.cashbackrequest')),
            ],
            options={
                'verbose_name': 'Фискальный чек',
                'verbose_name_plural': 'Фискальные чеки',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
