# Generated by Django 5.2.6 on 2026-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0004_fiscalreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackrequest',
            name='promotion',
            field=models.JSONField(blank=True, help_text='Применённая акция: {id, title, kind, basePrice, discount, gift}', null=True),
        ),
    ]
