# Generated by Django 5.2.6 on 2026-09-28 18:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(choices=[('rooms', 'Номера'), ('spa', 'SPA'), ('food', 'Рестораны'), ('pools', 'Бассейны'), ('sport', 'Спорт')], max_length=20, primary_key=True, serialize=False)),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('cover', models.CharField(blank=True, max_length=500, verbose_name='Обложка')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Доля кешбека')),
                ('max_points_share', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Доля оплаты баллами')),
                ('methods', models.JSONField(default=list, verbose_name='Способы доплаты')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Точка обслуживания',
                'verbose_name_plural': 'Точки обслуживания',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.SlugField(help_text='Стабильный: на него ссылаются заявки, история, сторис', max_length=60, primary_key=True, serialize=False, verbose_name='Slug')),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Короткая строка')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='Главное фото')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Галерея')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, сом')),
                ('pricing', models.JSONField(default=dict, verbose_name='Тип цены')),
                ('tag', models.JSONField(blank=True, default=dict, verbose_name='Бейдж')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='Описание')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Что входит')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.outlet')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Ставка')),
                ('tag', models.JSONField(blank=True, default=dict, verbose_name='Бейдж')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Акция на услугу',
                'verbose_name_plural': 'Акции на услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
