# Generated by Django 5.2.6 on 2026-10-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_venues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='Описание')),
                ('tag', models.JSONField(blank=True, default=dict, help_text='«−20%», «Суперцена»', verbose_name='Бейдж')),
                ('kind', models.CharField(choices=[('percent', 'Скидка в процентах'), ('amount', 'Скидка суммой'), ('specialPrice', 'Специальная цена'), ('gift', 'Бесплатная услуга в подарок'), ('bundle', 'Пакет (комбо)'), ('nPlusOne', 'N+1')], max_length=20, verbose_name='Вид')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Размер')),
                ('scope', models.CharField(choices=[('items', 'Услуги'), ('sections', 'Разделы'), ('venues', 'Объекты'), ('all', 'Все объекты')], default='items', max_length=10, verbose_name='Охват')),
                ('bundle_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена пакета')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0 — пн … 6 — вс; пусто — все', verbose_name='Дни недели')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='С')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='До')),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимум (ночей, гостей, единиц)')),
                ('min_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная сумма заказа, сом')),
                ('audience', models.CharField(choices=[('all', 'Все гости'), ('members', 'Участники программы лояльности'), ('tiers', 'Участники выбранных уровней'), ('groups', 'Группы (от N человек)'), ('children', 'Дети')], default='all', max_length=10, verbose_name='Для кого')),
                ('tiers', models.JSONField(blank=True, default=list, help_text='Для «участники выбранных уровней»', verbose_name='Уровни')),
                ('group_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Группа от, человек')),
                ('stackable', models.BooleanField(default=False, verbose_name='Суммируется с другими акциями')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита', null=True, verbose_name='Лимит использований')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Включена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_items', models.ManyToManyField(blank=True, related_name='bundles', to='catalog.item', verbose_name='Состав пакета')),
                ('gift_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item', verbose_name='Услуга в подарок')),
                ('items', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.item', verbose_name='Услуги')),
                ('sections', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.section', verbose_name='Разделы')),
                ('venues', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.venue', verbose_name='Объекты')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
