# Generated by Django 5.2.6 on 2026-10-10 19:03

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('app', models.CharField(choices=[('resort', 'bayturapp (Resort & Spa)'), ('sk', 'Baytur S&K')], max_length=10, primary_key=True, serialize=False)),
                ('min_version_ios', models.CharField(default='0.1.0', max_length=20)),
                ('min_version_android', models.CharField(default='0.1.0', max_length=20)),
                ('maintenance', models.BooleanField(default=False, verbose_name='Техработы')),
                ('maintenance_message', models.JSONField(blank=True, default=dict, verbose_name='Текст техработ')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='showcase', serialize=False, to='catalog.venue')),
                ('hero_image', models.CharField(blank=True, max_length=500, verbose_name='Шапка (день)')),
                ('hero_image_night', models.CharField(blank=True, max_length=500, verbose_name='Шапка (ночь)')),
                ('facts', models.JSONField(blank=True, default=list, help_text='[{"ru": "3 000 м", …}]', verbose_name='Факты')),
                ('cta', models.JSONField(blank=True, default=dict, verbose_name='Кнопка')),
                ('cta_section', models.CharField(blank=True, max_length=40, verbose_name='Кнопка ведёт в раздел')),
                ('tiles', models.JSONField(blank=True, default=list, help_text='[{"section", "icon", "title": {...}}]', verbose_name='Плитки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Объект (режим)', 'verbose_name_plural': 'Объекты (режимы)'},
        ),
        migrations.AddField(
            model_name='item',
            name='action',
            field=models.CharField(choices=[('book_stay', 'Бронь проживания'), ('book_slot', 'Запись на время'), ('book_seats', 'Места в рейсе'), ('buy_ticket', 'Купить билет'), ('pay_cashier', 'Оплата у кассира'), ('request', 'Заявка администратору'), ('info', 'Только информация')], default='pay_cashier', max_length=20, verbose_name='Кнопка в карточке'),
        ),
        migrations.AddField(
            model_name='item',
            name='capacity',
            field=models.JSONField(blank=True, help_text='{"minGuests": 1, "maxGuests": 6}', null=True, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='item',
            name='cashback_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Ставка кешбека'),
        ),
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AddField(
            model_name='item',
            name='methods',
            field=models.JSONField(blank=True, help_text='Пусто — из раздела', null=True, verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='Цену уточняйте'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_up_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до (вилка)'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('night', 'ночь'), ('day', 'сутки'), ('hour', 'час'), ('min30', '30 минут'), ('hours3', '3 часа'), ('session', 'сеанс'), ('person', 'человек'), ('guest', 'гость'), ('visit', 'посещение'), ('vehicle_one_way', 'машина в одну сторону'), ('vehicle_round_trip', 'машина туда и обратно'), ('seat', 'место'), ('portion', 'порция'), ('piece', 'штука'), ('none', '—')], max_length=20, verbose_name='Единица'),
        ),
        migrations.AddField(
            model_name='section',
            name='cashback_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Пусто — базовая ставка программы', max_digits=5, null=True, verbose_name='Ставка кешбека'),
        ),
        migrations.AddField(
            model_name='section',
            name='cover',
            field=models.CharField(blank=True, max_length=500, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='section',
            name='default_unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Единица по умолчанию'),
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='section',
            name='key',
            field=models.SlugField(blank=True, help_text='Короткий id раздела в режиме: skipass, rental, stay…', max_length=40, verbose_name='id в приложении'),
        ),
        migrations.AddField(
            model_name='section',
            name='kind',
            field=models.CharField(blank=True, choices=[('stay', 'Проживание'), ('pass', 'Скипасс, билеты'), ('rental', 'Прокат'), ('menu', 'Меню'), ('procedure', 'Процедуры'), ('transfer', 'Трансфер'), ('extra', 'Доп. услуги'), ('info', 'Справка')], max_length=20, verbose_name='Тип раздела'),
        ),
        migrations.AddField(
            model_name='section',
            name='methods',
            field=models.JSONField(blank=True, help_text='Пусто — из раздела программы', null=True, verbose_name='Способы оплаты'),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle',
            field=models.JSONField(blank=True, default=dict, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='venue',
            name='accent',
            field=models.CharField(default='#C6F24E', max_length=9, verbose_name='Цвет в админке'),
        ),
        migrations.AddField(
            model_name='venue',
            name='app',
            field=models.CharField(choices=[('resort', 'bayturapp (Resort & Spa)'), ('sk', 'Baytur S&K')], default='resort', max_length=10, verbose_name='Приложение'),
        ),
        migrations.AddField(
            model_name='venue',
            name='early_booking_enabled',
            field=models.BooleanField(default=False, verbose_name='Ранняя бронь'),
        ),
        migrations.AddField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='venue',
            name='icon',
            field=models.CharField(blank=True, max_length=500, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Объект открыт'),
        ),
        migrations.AddField(
            model_name='venue',
            name='maps_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Карты (ссылка)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='venue',
            name='timezone',
            field=models.CharField(default='Asia/Bishkek', max_length=40, verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='venue',
            name='two_gis_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='2ГИС (ссылка)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.SlugField(help_text='resort, ski, kymyz', max_length=40, primary_key=True, serialize=False, verbose_name='Режим'),
        ),
        migrations.CreateModel(
            name='EternalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in', models.JSONField(default=list, help_text='["ski"]', verbose_name='Показывать в режимах')),
                ('title', models.JSONField(default=dict, verbose_name='Заголовок')),
                ('lead', models.JSONField(blank=True, default=dict, verbose_name='Подводка')),
                ('cover', models.CharField(blank=True, max_length=500, verbose_name='Обложка')),
                ('slides', models.JSONField(blank=True, default=list, verbose_name='Слайды')),
                ('early_bonus', models.JSONField(blank=True, null=True, verbose_name='Бонус за раннюю бронь')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eternal_about', to='catalog.venue', verbose_name='О каком режиме')),
            ],
            options={
                'verbose_name': '«Вечная новость»',
                'verbose_name_plural': '«Вечные новости»',
            },
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, verbose_name='Заголовок')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Строки')),
                ('sort_order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='catalog.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справка',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.JSONField(blank=True, default=dict, verbose_name='Когда (текст)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('title', models.JSONField(default=dict, verbose_name='Заголовок')),
                ('place', models.JSONField(blank=True, default=dict, verbose_name='Место')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='Картинка')),
                ('article_id', models.CharField(blank=True, max_length=60, verbose_name='Статья (id)')),
                ('publish_from', models.DateTimeField(blank=True, null=True, verbose_name='Показывать с')),
                ('publish_to', models.DateTimeField(blank=True, null=True, verbose_name='Показывать по')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='catalog.venue', verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Новость главной',
                'verbose_name_plural': 'Новости главной',
                'ordering': ['sort_order', 'date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('starts_at', models.DateField(verbose_name='Начало')),
                ('ends_at', models.DateField(verbose_name='Конец')),
                ('early_booking_from', models.DateField(blank=True, null=True, verbose_name='Ранняя бронь с')),
                ('off_season_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.venue', verbose_name='Режим в межсезонье перед этим сезоном')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.venue', verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'year'), name='season_venue_year_unique')],
            },
        ),
        migrations.AlterField(
            model_name='outlet', name='venue',
            field=models.ForeignKey(default=apps.catalog.models.default_venue,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='outlets',
                                    to='catalog.venue', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='item', name='venue',
            field=models.ForeignKey(default=apps.catalog.models.default_venue,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='items',
                                    to='catalog.venue', verbose_name='Объект'),
        ),
]
