# Generated by Django 5.2.6 on 2026-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='note',
            field=models.JSONField(blank=True, default=dict, help_text='«по будням», «от 3 ночей»', verbose_name='Условие (коротко)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
    ]
