# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_operation_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cashback', 'Начисление'), ('spend', 'Списание'), ('refund', 'Возврат'), ('adjustment', 'Корректировка'), ('expire', 'Сгорание'), ('forfeit', 'Списание при удалении')], max_length=20)),
                ('points', models.BigIntegerField()),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item_id', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.JSONField(blank=True, help_text='Fallback-название, если услугу удалили', null=True)),
                ('reason', models.TextField(blank=True, help_text='Причина корректировки/возврата — клиент её видит')),
                ('affects_lifetime', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30)),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('short', models.JSONField(default=dict, verbose_name='Коротко (1–2 слова)')),
                ('description', models.JSONField(default=dict, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Привилегия',
                'verbose_name_plural': 'Привилегии',
                'ordering': ['tier__from_points', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platinum', 'Платина'), ('diamond', 'Бриллиант')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('from_points', models.PositiveBigIntegerField(verbose_name='Порог, баллов (lifetime)')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['from_points'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='members.member')),
                ('balance', models.BigIntegerField(default=0)),
                ('reserved', models.BigIntegerField(default=0)),
                ('lifetime', models.BigIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Последнее реальное действие: заявка, начисление, списание', null=True)),
                ('expiry_warned', models.JSONField(blank=True, default=list, help_text='За сколько дней уже предупредили')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
