# Generated by Django 5.2.6 on 2026-09-28 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashback', '0002_initial'),
        ('complaints', '0002_initial'),
        ('loyalty', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensations', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='operation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='members.member'),
        ),
        migrations.AddField(
            model_name='operation',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Исходная операция для refund / adjustment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='cashback.cashbackrequest'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privileges', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['member', '-at'], name='loyalty_ope_member__2d6b36_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='wallet_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('balance'))), name='wallet_reserved_lte_balance'),
        ),
    ]
