# Generated by Django 5.2.6 on 2026-10-02 19:45

from django.db import migrations, models


def fill_colors(apps, schema_editor):
    from apps.loyalty.models import DEFAULT_TIER_COLORS, FALLBACK_TIER_COLORS
    Tier = apps.get_model('loyalty', 'Tier')
    for t in Tier.objects.all():
        if not t.colors:
            t.colors = DEFAULT_TIER_COLORS.get(t.id, FALLBACK_TIER_COLORS)
            t.save(update_fields=['colors'])



class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Градиент: 3 цвета #RRGGBB'),
        ),
        migrations.AddField(
            model_name='tier',
            name='medal',
            field=models.CharField(blank=True, max_length=500, verbose_name='Картинка медали (необязательно)'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='id',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.RunPython(fill_colors, migrations.RunPython.noop),
    ]
