# Generated by Django 5.2.6 on 2026-10-05 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_tiers_dynamic'),
        ('members', '0002_member_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Иконка')),
                ('type', models.CharField(choices=[('consecutive_years', 'N лет подряд с покупками'), ('member_years', 'N лет в программе'), ('requests_count', 'N заявок'), ('nights', 'N ночей'), ('spend_som', 'Потратить N сом'), ('categories_used', 'Попробовать категории'), ('lifetime_points', 'Накопить N баллов за всё время'), ('manual', 'Отмечает администратор')], max_length=30, verbose_name='Тип')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('scope', models.CharField(choices=[('lifetime', 'За всё время'), ('period', 'За текущий период')], default='lifetime', max_length=10, verbose_name='Область')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать клиенту')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('calendar_year', 'Календарный год'), ('anniversary', 'Год от получения уровня')], default='calendar_year', max_length=20, verbose_name='Период')),
                ('timezone', models.CharField(default='Asia/Bishkek', max_length=40, verbose_name='Часовой пояс')),
                ('floor_depth', models.PositiveSmallIntegerField(default=1, verbose_name='Глубина пола')),
                ('carry_over', models.BooleanField(default=False, verbose_name='Переносить излишек «Нынешних» при повышении')),
                ('at_risk_days', models.PositiveSmallIntegerField(default=60, verbose_name='Предупреждать о риске за N дней')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки балловой системы',
                'verbose_name_plural': 'Настройки балловой системы',
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(blank=True, max_length=20)),
                ('progress', models.BigIntegerField(default=0)),
                ('target', models.BigIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('current', models.BigIntegerField()),
                ('limit_before', models.BigIntegerField(blank=True, null=True)),
                ('limit_after', models.BigIntegerField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('retained', 'Подтверждён'), ('dropped', 'Понижен'), ('promoted_in_period', 'Получен в этом периоде'), ('floor', 'Вечный'), ('not_required', 'Подтверждение не нужно')], max_length=20)),
                ('settings_version', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='TierAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('entry', 'Для получения'), ('retention', 'Для подтверждения'), ('both', 'Оба')], default='both', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TierChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cause', models.CharField(choices=[('promotion', 'Повышение'), ('period_drop', 'Понижение при закрытии периода'), ('admin', 'Администратор'), ('migration', 'Миграция')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TierLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.BigIntegerField(default=0)),
                ('source', models.CharField(choices=[('period_close', 'Закрытие периода'), ('admin', 'Администратор'), ('migration', 'Миграция')], default='period_close', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='privilege',
            options={'ordering': ['tier__order', 'sort_order', 'id'], 'verbose_name': 'Привилегия', 'verbose_name_plural': 'Привилегии'},
        ),
        migrations.AlterModelOptions(
            name='tier',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='expiry_warned',
        ),
        migrations.AddField(
            model_name='operation',
            name='d_current',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='d_lifetime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='d_reserved',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='period_key',
            field=models.CharField(blank=True, help_text='В каком периоде засчитаны «Нынешние»', max_length=20),
        ),
        migrations.AddField(
            model_name='tier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='tier',
            name='can_be_floor',
            field=models.BooleanField(default=True, verbose_name='Может стать вечным'),
        ),
        migrations.AddField(
            model_name='tier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='drop_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loyalty.tier', verbose_name='При потере переходит на (пусто — на один ниже)'),
        ),
        migrations.AddField(
            model_name='tier',
            name='entry_n',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N для «любые N из M»'),
        ),
        migrations.AddField(
            model_name='tier',
            name='entry_rule',
            field=models.CharField(choices=[('all', 'Все задания'), ('any_n', 'Любые N из M')], default='all', max_length=10, verbose_name='Задания для получения'),
        ),
        migrations.AddField(
            model_name='tier',
            name='glow',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет свечения #RRGGBB'),
        ),
        migrations.AddField(
            model_name='tier',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='tier',
            name='limit_bonus',
            field=models.PositiveBigIntegerField(default=10000, verbose_name='Надбавка к лимиту'),
        ),
        migrations.AddField(
            model_name='tier',
            name='limit_only_grows',
            field=models.BooleanField(default=True, verbose_name='Лимит только растёт'),
        ),
        migrations.AddField(
            model_name='tier',
            name='min_limit',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Минимальный лимит'),
        ),
        migrations.AddField(
            model_name='tier',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок снизу вверх'),
        ),
        migrations.AddField(
            model_name='tier',
            name='retention',
            field=models.CharField(choices=[('none', 'Не нужно'), ('points', 'Баллы'), ('points_and_achievements', 'Баллы и задания')], default='points', max_length=30, verbose_name='Подтверждение каждый год'),
        ),
        migrations.AddField(
            model_name='tier',
            name='threshold',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Порог, «Нынешних» баллов за период'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='current',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='max_reached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='period_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='risk_warned',
            field=models.JSONField(blank=True, default=dict, help_text='{period: ключ, days: [за сколько дней уже предупредили]}'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='settings_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tier_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('cashback', 'Начисление'), ('spend', 'Списание'), ('reserve', 'Резерв'), ('release', 'Снятие резерва'), ('refund', 'Возврат'), ('reversal', 'Отмена начисления'), ('adjustment', 'Корректировка'), ('period_reset', 'Сброс «Нынешних» (новый период)'), ('promotion_reset', 'Сброс «Нынешних» (новый уровень)'), ('expire', 'Сгорание'), ('forfeit', 'Списание при удалении')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Исходная операция для refund / reversal / adjustment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.operation'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('current__gte', 0)), name='wallet_current_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('lifetime__gte', 0)), name='wallet_lifetime_gte_0'),
        ),
        migrations.AddField(
            model_name='memberachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_states', to='loyalty.achievement'),
        ),
        migrations.AddField(
            model_name='memberachievement',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberachievement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='members.member'),
        ),
        migrations.AddField(
            model_name='periodresult',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_results', to='members.member'),
        ),
        migrations.AddField(
            model_name='periodresult',
            name='tier_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='periodresult',
            name='tier_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='tierachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_links', to='loyalty.achievement'),
        ),
        migrations.AddField(
            model_name='tierachievement',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_achievements', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='tierchange',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tierchange',
            name='from_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='tierchange',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_changes', to='members.member'),
        ),
        migrations.AddField(
            model_name='tierchange',
            name='to_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddField(
            model_name='tierlimit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_limits', to='members.member'),
        ),
        migrations.AddField(
            model_name='tierlimit',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loyalty.tier'),
        ),
        migrations.AddConstraint(
            model_name='memberachievement',
            constraint=models.UniqueConstraint(fields=('member', 'achievement', 'period_key'), name='member_achievement_unique'),
        ),
        migrations.AddConstraint(
            model_name='periodresult',
            constraint=models.UniqueConstraint(fields=('member', 'period_key'), name='period_result_unique'),
        ),
        migrations.AddConstraint(
            model_name='tierachievement',
            constraint=models.UniqueConstraint(fields=('tier', 'achievement'), name='tier_achievement_unique'),
        ),
        migrations.AddConstraint(
            model_name='tierlimit',
            constraint=models.UniqueConstraint(fields=('member', 'tier'), name='tier_limit_unique'),
        ),
    ]
