# Generated by Django 5.2.6 on 2026-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_more_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, choices=[('calendar', 'calendar'), ('ticket', 'ticket'), ('users', 'users'), ('bed', 'bed'), ('spa', 'spa'), ('food', 'food'), ('star', 'star'), ('gift', 'gift')], max_length=40, verbose_name='Иконка'),
        ),
    ]
