# Generated by Django 5.2.6 on 2026-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_achievement_icon_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='footnote',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сноска мелким шрифтом'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='group',
            field=models.SlugField(blank=True, max_length=40, verbose_name='Группа (апгрейдер)'),
        ),
        migrations.AddField(
            model_name='tier',
            name='cashback_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Баллы = Сумма × базовая ставка × (1 + надбавка / 100)', max_digits=6, verbose_name='Надбавка к кешбеку, %'),
        ),
        migrations.AddField(
            model_name='tier',
            name='permanent_lifetime',
            field=models.PositiveBigIntegerField(blank=True, help_text='Пусто — уровень не бывает постоянным', null=True, verbose_name='Навсегда: баллов за всё время'),
        ),
        migrations.AddField(
            model_name='tier',
            name='permanent_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Навсегда: лет в программе'),
        ),
        migrations.AlterField(
            model_name='tierchange',
            name='cause',
            field=models.CharField(choices=[('promotion', 'Повышение'), ('permanent', 'Постоянный статус'), ('period_drop', 'Понижение при закрытии периода'), ('admin', 'Администратор'), ('migration', 'Миграция')], max_length=20),
        ),
    ]
