# Generated by Django 5.2.6 on 2026-10-09 17:20

from django.db import migrations, models

GROUP_TITLES = {
    'points-rate': {'ru': 'Кешбек баллами', 'ky': 'Упай кешбеги', 'en': 'Cashback in points'},
    'late-checkout': {'ru': 'Поздний выезд', 'ky': 'Кеч чыгуу', 'en': 'Late check-out'},
    'room-upgrade': {'ru': 'Апгрейд номера', 'ky': 'Бөлмөнү жакшыртуу', 'en': 'Room upgrade'},
    'bai-club': {'ru': 'Bai Club', 'ky': 'Bai Club', 'en': 'Bai Club'},
    'welcome-gift': {'ru': 'Приветственный подарок', 'ky': 'Тосуу белеги', 'en': 'Welcome gift'},
}


def fill_group_titles(apps, schema_editor):
    Privilege = apps.get_model('loyalty', 'Privilege')
    for group, title in GROUP_TITLES.items():
        Privilege.objects.filter(group=group, group_title={}).update(group_title=title)


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_loyalty_v3_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='group_title',
            field=models.JSONField(blank=True, default=dict, verbose_name='Название группы'),
        ),
        migrations.RunPython(fill_group_titles, migrations.RunPython.noop),
    ]
