# Generated by Django 5.2.6 on 2026-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_privilege_rate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='modes',
            field=models.JSONField(blank=True, default=list, help_text='Пусто — везде', verbose_name='Режимы'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='modes',
            field=models.JSONField(blank=True, default=list, help_text='Пусто — везде; ["ski"] — только Тоо-Ашуу', verbose_name='Режимы'),
        ),
    ]
