# Generated by Django 5.2.6 on 2026-09-28 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20)),
                ('use_ru_fallback', models.BooleanField(default=False, verbose_name='Использовать ru вместо пустых переводов')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('tag', models.JSONField(blank=True, default=dict)),
                ('title', models.JSONField(default=dict)),
                ('lead', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='Абзацы {ru: [...], ky: [...], en: [...]}')),
                ('quote', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публикации')),
                ('minutes', models.PositiveSmallIntegerField(default=3, verbose_name='Время чтения, мин')),
                ('category', models.ForeignKey(blank=True, help_text='Куда ведёт «Открыть в каталоге»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20)),
                ('use_ru_fallback', models.BooleanField(default=False, verbose_name='Использовать ru вместо пустых переводов')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.JSONField(default=dict)),
                ('cta', models.JSONField(default=dict, verbose_name='Текст кнопки')),
                ('cutout', models.CharField(blank=True, max_length=500, verbose_name='PNG без фона')),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promos', to='content.article')),
            ],
            options={
                'verbose_name': 'Акция-баннер',
                'verbose_name_plural': 'Акции-баннеры',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResortEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20)),
                ('use_ru_fallback', models.BooleanField(default=False, verbose_name='Использовать ru вместо пустых переводов')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('when', models.JSONField(default=dict, verbose_name='Когда (свободный текст)')),
                ('place', models.JSONField(default=dict, verbose_name='Где')),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='content.article')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20)),
                ('use_ru_fallback', models.BooleanField(default=False, verbose_name='Использовать ru вместо пустых переводов')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Сторис',
                'verbose_name_plural': 'Сторис',
                'ordering': ['sort_order', 'category__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('title', models.JSONField(default=dict)),
                ('text', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, help_text='Услуга для кнопки «Получить кешбек»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content.story')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
