# Generated by Django 5.2.6 on 2026-10-10 19:03

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modes',
            field=models.JSONField(blank=True, default=apps.content.models.default_modes, verbose_name='Режимы'),
        ),
        migrations.AddField(
            model_name='promo',
            name='modes',
            field=models.JSONField(blank=True, default=apps.content.models.default_modes, verbose_name='Режимы'),
        ),
        migrations.AddField(
            model_name='resortevent',
            name='modes',
            field=models.JSONField(blank=True, default=apps.content.models.default_modes, verbose_name='Режимы'),
        ),
        migrations.AddField(
            model_name='story',
            name='modes',
            field=models.JSONField(blank=True, default=apps.content.models.default_modes, verbose_name='Режимы'),
        ),
    ]
