# Generated by Django 5.2.6 on 2026-09-28 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('deletion', 'Deletion')], default='login', max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('burned', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Условия программы'), ('privacy', 'Политика конфиденциальности'), ('deletion', 'Страница удаления аккаунта')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('url', models.JSONField(default=dict, verbose_name='URL на 3 языках')),
                ('requires_acceptance', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['kind', '-published_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='legal_kind_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=12, unique=True, verbose_name='Номер участника')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (E.164)')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Пол')),
                ('member_since', models.DateField(default=django.utils.timezone.localdate, verbose_name='Участник с')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deactivated', 'Удалён (хранится)'), ('purged', 'Стёрт'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус')),
                ('blocked_reason', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча'), ('en', 'English')], default='ru', max_length=2)),
                ('notify_cashback', models.BooleanField(default=True)),
                ('notify_promos', models.BooleanField(default=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('purge_immediately', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False, verbose_name='Тестовый аккаунт для сторов')),
                ('first_device_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone',), name='member_phone_unique')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('marketing', 'Marketing')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('granted', models.BooleanField(default=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='members.member')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='MemberRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family', models.CharField(db_index=True, max_length=32)),
                ('device_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='members.member')),
            ],
        ),
    ]
