# Generated by Django 5.2.6 on 2026-10-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple ID')], max_length=10)),
                ('subject', models.CharField(max_length=255, verbose_name='sub провайдера')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='members.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='social_provider_subject_unique'), models.UniqueConstraint(fields=('member', 'provider'), name='social_member_provider_unique')],
            },
        ),
    ]
