# Generated by Django 5.2.6 on 2026-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
