# Generated by Django 5.2.6 on 2026-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='body',
            field=models.JSONField(blank=True, default=dict, help_text='«## Заголовок», «- пункт», пустая строка — абзац; {phone}, {whatsapp}, {purge_days}', verbose_name='Текст на 3 языках (для страницы /legal/<документ>)'),
        ),
    ]
