# Generated by Django 5.2.6 on 2026-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Сменить временный пароль при входе'),
        ),
    ]
