# Generated by Django 5.2.6 on 2026-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
        ('staff', '0003_roles_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='pin_failed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Вход администратора в приложение; сотрудник не подтверждает заявки своего клиентского аккаунта', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Директор'), ('staff', 'Администратор кассы')], default='staff', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddConstraint(
            model_name='staffuser',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='staff_phone_unique'),
        ),
    ]
