# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=40)),
                ('params', models.JSONField(default=dict)),
                ('fmt', models.CharField(default='xlsx', max_length=5)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file', models.FileField(blank=True, storage=apps.common.storage.private_storage, upload_to='exports/%Y/%m/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=36)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('at', models.DateTimeField(db_index=True)),
                ('props', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=36, unique=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
        ),
    ]
