# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_complaint_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(unique=True)),
                ('subtype', models.CharField(blank=True, choices=[('not_credited', 'Не начислили'), ('credited_less', 'Начислили меньше'), ('overcharged', 'Списали лишнее'), ('other', 'Другое')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], db_index=True, default='new', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('first_reply_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.JSONField(default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тема обращения',
                'verbose_name_plural': 'Темы обращений',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('client', 'Клиент'), ('resort', 'Курорт')], max_length=10)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.JSONField(default=dict)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
