# Generated by Django 5.2.6 on 2026-09-28 18:43

import apps.common.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashback', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.common.ids.new_payment_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма, сом')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('redirect_url', models.URLField(blank=True, max_length=1000)),
                ('qr_payload', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('params', models.JSONField(default=dict)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='cashback.cashbackrequest')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
